repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.0
  hooks:
    - id: flake8

- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
    - id: mypy

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      args: [--fail-under=80, --verbose]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      args: ["--ignore=D107,D204,D407,D213,D212,D413,D406"]

- repo: local
  hooks:
    - id: set_hooks # This should match the script file name
      name: set-hooks
      entry: 'sh .set_hooks.sh'
      types: [bash]
      pass_filenames: false
      language: system
